name: Generate Snake

on:
  schedule:
    # Menjalankan aksi setiap 24 jam
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Memeriksa repositori
      - uses: actions/checkout@v2

      # Menghasilkan animasi ular
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Mendorong perubahan ke cabang output
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: output
          force: true
